services:
  timescaledb:
    image: timescale/timescaledb-ha:pg17.6-ts2.22.1
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo19@2025
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
      - "./_data/postgresql:/home/postgres/pgdata/data"

  odoo19:
    image: odoo:19
    user: root
    depends_on:
      - timescaledb
    ports:
      - "10019:8069"
      - "20019:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=timescaledb
      - USER=odoo
      - PASSWORD=odoo19@2025
      - PIP_BREAK_SYSTEM_PACKAGES=1
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      - ./entrypoint.sh:/entrypoint.sh
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
    